language: ruby
cache: bundler
rvm:
  - 2.3.4
  - 2.4.1
before_script:
  - psql -c 'CREATE DATABASE enju_event_dummy_test'
  - psql enju_event_dummy_test -c 'CREATE EXTENSION pgcrypto'
  - bundle exec rake db:migrate
after_script:
  - bundle exec codeclimate-test-reporter
services:
  - redis-server
env:
  - DB=postgresql
notifications:
  slack:
    secure: hNnknSF8o2Gv0BKtligsFO07rurlizyDrjKEnzE1qV9U0GALZlyUigurJUxAhgUXNfI73SRR6zmfQl6+m/B6jGp2UF8S+c9gsuv7lWZPz+BpvZ2Eit3YW1hA7+o1f3Toc7UHDTvfowo8uyo5pKFLtVfsZVu5gXnT22+NBmPg9vw=
sudo: false
addons:
  postgresql: "9.5"
