version: 2
jobs:
  build:
    working_directory: ~/enju_event
    docker:
      - image: circleci/ruby:2.4
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          PGUSER: postgres
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: enju_event_dummy_test
    steps:
      - checkout
      - restore_cache:
          keys:
            - rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
            - rails-demo-bundle-v2-
      - run: bundle update
      - run:
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          command: sudo apt install -y openjdk-8-jre-headless
      - run: bundle exec rake db:create RAILS_ENV=test
      - run: bundle exec rake db:migrate RAILS_ENV=test
      - run: bundle exec rake app:sunspot:solr:start RAILS_ENV=test
      - run:
          command: |
            mkdir /tmp/test-results
            bundle exec rspec --format progress \
                              --format RspecJunitFormatter \
                              --out /tmp/test-results/rspec.xml \
                              --format progress
      - save_cache:
          key: rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
